config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post '/login', controller: :users, action: :login
  delete '/logout', controller: :users, action: :logout
  root 'users#new'
  get 'welcomes/index'
  resources :teachers
  resources :students do
    collection do
      get "generate_excel"
    end
  end
  resources :standards
  resources :classrooms
  resources :addresses
  resources :attendances

  namespace :api do
    namespace :v1 do
      resources :students
      resources :districts
    end
  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      # if user.admin?
      #   can :manage, :all
      # else
      #   can :read, :all
      # end
      if user.present?  # additional permissions for logged in users (they can manage their posts)
        # can :manage, Student, user_id: user.id
        if user.login_type == "Teacher"  # additional permissions for administrators
          can [:read, :update, :destroy], User, login_type: 'Teacher'
          # can [:read, :update, :destroy], Student #if you want to give access to teacher for delete student.
          can [:read, :update], Student
        end
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :country
  belongs_to :state
  belongs_to :district
  belongs_to :taluka
  belongs_to :user
  validates :pincode, presence: true, numericality: true, length: { is: 6 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def soft_delete
    update(deleted_at: Time.current)
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student
  belongs_to :teacher
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  has_many :students
  belongs_to :teacher
  belongs_to :standard
  validates :medium, :division, :intake, presence: true
  validates :intake, numericality: true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states
  has_many :addresses
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :state
  has_many :talukas
  has_many :addresses
end

app/models/hard_worker.rb
class HardWorker
  include Sidekiq::Worker

  def perform(count)
    count.times do |number|
      Role.create(name: "sidekiq#{number}")
    end
  end
end

app/models/standard.rb
class Standard < ApplicationRecord
  has_many :classrooms
  has_many :students
  validates :name, presence: true
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :districts
  has_many :addresses
end

app/models/student.rb
class Student < ApplicationRecord
  has_one :attendance
  has_one :user, as: :login

  belongs_to :standard
  belongs_to :classroom
  has_many :addresses

  validates :first_name,
            :middle_name,
            :last_name,
            :mother_name,
            :date_of_birth,
            :aadhaar_card_number,
            presence: true
  validates :aadhaar_card_number, numericality: true, uniqueness: true, length: { is: 12 }

  after_create :create_user

  private

  def create_user
    User.create(
      username: (last_name + '_' + aadhaar_card_number.last(4)).to_s,
      password: '123456',
      login: self
    )
  end
end

app/models/taluka.rb
class Taluka < ApplicationRecord
  belongs_to :district
  has_many :addresses
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_one :classroom
  has_one :user, as: :login
  has_one :attendance
  has_many :addresses

  validates :gender, inclusion: %w[male female transgender]
  validates :first_name, :middle_name, :last_name, :mother_name, :date_of_birth, :date_of_join, :gender, presence: true
  validates :contact, presence: true, uniqueness: true, numericality: true, length: { in: 10..15 }
  validates :is_active, acceptance: true

  after_create :create_user

  private

  def create_user
    User.create(
      username: (last_name + '_' + contact.last(4)).to_s,
      password: '123456',
      login: self
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :addresses
  belongs_to :login, polymorphic: true
  validates :username, presence: true
  validates :password, presence: true, length: { minimum: 6 }

  def self.authenticate(username, password)
    User.find_by(username: username, password: password)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
    @current_user_role = current_user.login_type
    if @current_user_role == 'Headmaster'
      @teachers = Teacher.all
      @students = Student.all
    elsif @current_user_role == 'Teacher'
      @students = Teacher.find(current_user.login_id).classroom.students.includes(:standard)
    else @current_user_role == 'Student'
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
  def teacher_full_name(teacher)
    teacher.first_name + ' ' + teacher.last_name
  end
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/_dashboard_headmaster.html.erb
<h1>headmaster</h1>
<h3><%= link_to "Add New Standard", new_standard_path %></h3>
<h3><%=link_to "New Classroom", new_classroom_path%></h3>
<h3><%=link_to "New Teacher", new_teacher_path%></h3>
<h3><%=link_to "New Student", new_student_path%></h3>

app/views/welcomes/_dashboard_student.html.erb
<h1>student</h1>

<h1>No data available</h1>

app/views/welcomes/_dashboard_teacher.html.erb
<h3><%= link_to "Add New Standard", new_standard_path %></h3>
<h3><%=link_to "New Classroom", new_classroom_path%></h3>
<h3><%=link_to "New Teacher", new_teacher_path%></h3>
<h3><%=link_to "New Student", new_student_path%></h3>
<h3><%=link_to "Generate student excelsheet", generate_excel_students_path(format: :xlsx)%></h3>

<h1>teacher</h1>

<h3><%=link_to "Home", welcomes_index_path%></h3>
<h3><%=link_to "New Classroom", new_classroom_path%></h3>
<table>
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Standard</th>
      <th>Action</th>
    </tr>
    <tbody>
      <%@students.each do |student|%>
        <tr>
          <td><%=student_full_name student%></td>
          <td><%=student.standard.name%></td>
          <td><%=link_to "Edit", edit_student_path(student)%></td>
          <td><%=link_to "Address", new_address_path(user: student.user.id)%></td>
        </tr>
      <%end%>
    </tbody>
  </thead>
</table>

app/views/welcomes/index.html.erb
<h1>Welcome to new page</h1>

<%#= render "welcomes/index?user=#{@user.id}"%>

<h1><%= link_to "LogOut", logout_path, method: :delete %></h1>
<% if @current_user_role == "Headmaster"%>
  <%= render "welcomes/dashboard_headmaster"%>
<% elsif @current_user_role == "Teacher"%>
  <%= render "welcomes/dashboard_teacher"%>
<% else @current_user_role == "Student"%>
  <%= render "welcomes/dashboard_student"%>
<% end%>