config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post '/login', controller: :users, action: :login
  delete '/logout', controller: :users, action: :logout
  root 'users#new'
  get 'welcomes/index'
  resources :teachers
  resources :students do
    collection do
      get "generate_excel"
    end
  end
  resources :standards
  resources :classrooms
  resources :addresses
  resources :attendances

  namespace :api do
    namespace :v1 do
      resources :students
      resources :districts
    end
  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      # if user.admin?
      #   can :manage, :all
      # else
      #   can :read, :all
      # end
      if user.present?  # additional permissions for logged in users (they can manage their posts)
        # can :manage, Student, user_id: user.id
        if user.login_type == "Teacher"  # additional permissions for administrators
          can [:read, :update, :destroy], User, login_type: 'Teacher'
          # can [:read, :update, :destroy], Student #if you want to give access to teacher for delete student.
          can [:read, :update], Student
        end
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :country
  belongs_to :state
  belongs_to :district
  belongs_to :taluka
  belongs_to :user
  validates :pincode, presence: true, numericality: true, length: { is: 6 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def soft_delete
    update(deleted_at: Time.current)
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student
  belongs_to :teacher
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  has_many :students
  belongs_to :teacher
  belongs_to :standard
  validates :medium, :division, :intake, presence: true
  validates :intake, numericality: true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states
  has_many :addresses
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :state
  has_many :talukas
  has_many :addresses
end

app/models/hard_worker.rb
class HardWorker
  include Sidekiq::Worker

  def perform(count)
    count.times do |number|
      Role.create(name: "sidekiq#{number}")
    end
  end
end

app/models/standard.rb
class Standard < ApplicationRecord
  has_many :classrooms
  has_many :students
  validates :name, presence: true
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :districts
  has_many :addresses
end

app/models/student.rb
class Student < ApplicationRecord
  has_one :attendance
  has_one :user, as: :login

  belongs_to :standard
  belongs_to :classroom
  has_many :addresses

  validates :first_name,
            :middle_name,
            :last_name,
            :mother_name,
            :date_of_birth,
            :aadhaar_card_number,
            presence: true
  validates :aadhaar_card_number, numericality: true, uniqueness: true, length: { is: 12 }

  after_create :create_user

  private

  def create_user
    User.create(
      username: (last_name + '_' + aadhaar_card_number.last(4)).to_s,
      password: '123456',
      login: self
    )
  end
end

app/models/taluka.rb
class Taluka < ApplicationRecord
  belongs_to :district
  has_many :addresses
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_one :classroom
  has_one :user, as: :login
  has_one :attendance
  has_many :addresses

  validates :gender, inclusion: %w[male female transgender]
  validates :first_name, :middle_name, :last_name, :mother_name, :date_of_birth, :date_of_join, :gender, presence: true
  validates :contact, presence: true, uniqueness: true, numericality: true, length: { in: 10..15 }
  validates :is_active, acceptance: true

  after_create :create_user

  private

  def create_user
    User.create(
      username: (last_name + '_' + contact.last(4)).to_s,
      password: '123456',
      login: self
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :addresses
  belongs_to :login, polymorphic: true
  validates :username, presence: true
  validates :password, presence: true, length: { minimum: 6 }

  def self.authenticate(username, password)
    User.find_by(username: username, password: password)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :find_teacher, only: %i[edit update]
  before_action :build_teacher, only: %i[new create]

  def index
    @teachers = Teacher.all
  end

  def new; end

  def edit; end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      redirect_to teachers_path
      flash[:success] = 'Teacher Successfully Created'
    else
      render :new
      flash[:notice] = 'Teacher Not Create!'
    end
  end

  def update
    if @teacher.update_attributes(teacher_params)
      redirect_to teachers_path
      flash[:success] = 'Teacher Successfully Update'
    else
      render :edit
      flash[:notice] = 'Teacher Not Update!'
    end
  end

  private

  def find_teacher
    @teacher = Teacher.find(params[:id])
  end

  def build_teacher
    @teacher = Teacher.new
  end

  def teacher_params
    params.require(:teacher).permit(:first_name, :middle_name, :last_name, :mother_name, :date_of_birth, :date_of_join, :gender, :aadhaar_card_number, :education, :speciality, :contact, :alternate_contact, :address, :is_active)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
  def teacher_full_name(teacher)
    teacher.first_name + ' ' + teacher.last_name
  end
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/teachers/_form.html.erb
<%=form_for @teacher do |f|%>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@teacher.errors.count, "error") %> prohibited
        this teacher from being saved:
      </h2>
      <ul>
        <% @teacher.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%=f.text_field :first_name, placeholder: "First Name"%><br><br>
  <%=f.text_field :middle_name, placeholder: "Middle Name"%><br><br>
  <%=f.text_field :last_name, placeholder: "Last Name"%><br><br>
  <%=f.text_field :mother_name, placeholder: "Mother Name"%><br><br>
  Birth Date:- <%=f.date_field :date_of_birth%><br><br>
  Join Date:- <%=f.date_field :date_of_join%><br><br>
  Gender:-<br>
  Male<%=f.radio_button :gender, "Male"%>
  Female<%=f.radio_button :gender, "Female"%>
  Transgender<%=f.radio_button :gender, "Transgender"%><br><br>
  <%=f.text_field :aadhaar_card_number, placeholder: "Aadhaar Card Number"%><br><br>
  <%=f.text_field :education, placeholder: "Education"%><br><br>
  <%=f.text_field :speciality, placeholder: "Speciality"%><br><br>
  <%=f.text_field :contact, placeholder: "Contact"%><br><br>
  <%=f.text_field :alternate_contact, placeholder: "Alternate Contact"%><br><br>
  <%=f.text_area :address, placeholder: "Address"%><br><br>
  Is Active:- <%=f.check_box :is_active%><br><br>

  <%=f.submit%>
  <%=link_to "Back", teachers_path%>
<%end%>

app/views/teachers/edit.html.erb
<%=render 'form'%>

app/views/teachers/index.html.erb
<h3><%=link_to "Home", welcomes_index_path%></h3>
<h3><%=link_to "New teacher", new_teacher_path%></h3>
<table>
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Mother Name</th>
      <th>Gender</th>
      <th>Action</th>
    </tr>
    <tbody>
      <%@teachers.each do |teacher|%>
        <tr>
          <td><%="#{teacher.first_name} #{teacher.middle_name} #{teacher.last_name}"%></td>
          <td><%=teacher.mother_name%></td>
          <td><%=teacher.gender%></td>
          <td><%=link_to "Edit", edit_teacher_path(teacher)%></td>
          <td><%=link_to "Address", new_address_path(user: teacher.user.id)%></td>
        </tr>
      <%end%>
    </tbody>
  </thead>
</table>

app/views/teachers/new.html.erb
<%=render 'form'%>